### PR TITLE
squid:S1213 - The members of an interface declaration or class should…

### PR DESCRIPTION
**Pull request by m-ezzat**
This pull request is focused on resolving occurrences of Sonar rule squid:S1213 - The members of an interface declaration or class should appear in a pre-defined order

You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S1213

Please let me know if you have any questions.

M-Ezzat

### CODE REVIEW

**Comment by buremba** [comment]
I had to fix test errors before merging pull requests, could you please rebase the pr so that I can merge?

**Comment by buremba** [comment]
It seems that the refactoring engine removed `lastMessage` field from PostgresqlUserMailboxStorage class so maven complains about compilation error.

https://github.com/DevFactory/rakam/blob/release/the-members-of-an-interface-declaration-or-class-should-appear-in-a-pre-defined-order-fix-1/rakam-postgresql/src/main/java/org/rakam/postgresql/plugin/user/mailbox/PostgresqlUserMailboxStorage.java#L170

**Comment by m-ezzat** [comment]
Thanks for letting me know

**Comment by buremba** [comment]
Thanks!

**Pull request merged**
